### ISSUE TITLE
请教黄老师，这里的共享变量不需要保障线程间的可见性吗？

### ISSUE THREAD

**Issue by FoghostCn** [Viscent/javamtia#4]
https://github.com/Viscent/javamtia/blob/ce745c808806df6fcf0cca0d8d2eb54ddfdafa1c/JavaMultiThreadInAction/src/io/github/viscent/mtia/ch5/TimeoutWaitExample.java#L22

https://github.com/Viscent/javamtia/blob/ce745c808806df6fcf0cca0d8d2eb54ddfdafa1c/JavaMultiThreadInAction/src/io/github/viscent/mtia/ch5/case01/AlarmAgent.java#L29

上边两处的共享变量的可见性保障有些疑惑
从您书中下面的章节来看子线程对父线程的共享变量是没法保障可见性的，但是这里并没有什么措施保障可见性

> 清单 2- 8 　 线程 启动 与 可见 性 
```java

  public class ThreadStartVisibility {
    // 线程间的共享变量
    static int data = 0;
    public static void main(String[] args) {
      Thread thread = new Thread() {
        @Override
        public void run() {
          // 使当前线程休眠R毫秒（R的值为随机数）
          Tools.randomPause(50);
          // 读取并打印变量data的值
          System.out.println(data);
        }
      };
      // 在子线程thread启动前更新变量data的值
      data = 1;// 语句①
      thread.start();
      // 使当前线程休眠R毫秒（R的值为随机数）
      Tools.randomPause(50);
      // 在子线程thread启动后更新变量data的值
      data = 2;// 语句②
    }
  }
```
> 如果 我们 把 上述 程序 中的 语句 ② 注释 掉， 则 由于 main 线程 在 启动 其 子 线程 thread 之前 将 共享 变量 data 的 值 更新 为 1（ 见 语句 ①）， 因此 子 线程 thread 所 读取 到 的 共享 变量 data 的 值 一 定为 1。 这是 由于 父 线程 在 子 线程 启动 前 对 共享 变量 的 更新 对子 线程 的 可见 性 是有 保证 的； 如果 我们 没有 将 语句 ② 注释 掉， 那么 由于 父 线程 在 子 线程 启动 之后 对 共享 变量 的 更新 对子 线程 的 可见 性 是 没有 保证 的， 因此 子 线程 thread 此时 读取 到 的 共享 变量 data 的 值 可 能为 2， 也可能 仍然 为 1。 这就 解释 了 为什么 多次 运行 上述 程序 可以 发现 其 输出 可能 是“ 1”， 也可能 是“ 2”。

黄文海. Java多线程编程实战指南（核心篇） (Java多线程编程实战系列) (Kindle 位置 1142-1147). 电子工业出版社. Kindle 版本.

**Comment by Viscent** [comment]
第1个问题：
io/github/viscent/mtia/ch5/TimeoutWaitExample.java

这个清单中所有对共享变量ready变量的访问都是在**同步块**中进行的，也就是说可见性由**内部锁**来保证。

第2个问题：
io/github/viscent/mtia/ch5/case01/AlarmAgent.java
这个清单中所有对共享变量connectedToServer的访问（_除HeartbeartThread.run方法中的访问之外_）都是在**同步块**中进行的，也就是说可见性由**内部锁**来保证。

HeartbeartThread.run方法对connectedToServer并没有加锁（且connectedToServer本身我们也没有采用volatile修饰），这是因为HeartbeartThread（心跳线程）本身就是周期性地检测网络连接状况（并试图重连）的（例子中是每2秒一次），而在心跳线程休眠（即没有在检测网络连接状况）的时候，完全可能有其他线程（业务线程）会通过调用sendAlarm方法来上报告警消息，这时connectedToServer变量可能无法准确反映告警代理与告警服务器的网络连接状况。即，这种情形下connectedToServer==true的时候告警代理与告警服务器的网络实际上可能是断链的，因此这时告警上报会失败（实际的代码中对上报失败的告警消息是有重试机制来处理的）。换而言之，在心跳线程中我们无需保障其对connectedToServer的更新能够“立即”（即保障可见性）被其他线程“看到”，因此我们没有将其对connectedToServer的访问进行加锁，也没有用volatile修饰connectedToServer变量。

**Comment by FoghostCn** [comment]
非常感谢黄老师
